/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author keiver
 */
public class PanelMain_SerpientesyEscaleras extends javax.swing.JFrame {

    /**
     * Creates new form PanelMain_Triquitraque
     */
    public PanelMain_SerpientesyEscaleras() {
        setUndecorated(true);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));
        panelFondo.requestFocus();
        panelFondo.setOpaque(false);
        Border bordeBoton = BorderFactory.createLineBorder(new Color(0, 0, 0), 0);
        panelBoton.setBorder(bordeBoton);
    }

    public void setNombreJugador1(String nombre) {
        txtJugador1.setText(nombre);
    }

    public void setNombreJugador2(String nombre) {
        txtJugador2.setText(nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtTamañoTablero = new javax.swing.ButtonGroup();
        rbtJugadores = new javax.swing.ButtonGroup();
        panelFondo = new modelo.PanelRedondeado();
        lblCierre = new javax.swing.JLabel();
        lblTamaño = new javax.swing.JLabel();
        txtJugador2 = new javax.swing.JTextField();
        txtJugador1 = new javax.swing.JTextField();
        rbt15x15 = new javax.swing.JRadioButton();
        rbt10x10 = new javax.swing.JRadioButton();
        rbt13x13 = new javax.swing.JRadioButton();
        lblTitulo = new javax.swing.JLabel();
        txtJugador3 = new javax.swing.JTextField();
        txtJugador4 = new javax.swing.JTextField();
        panelBoton = new javax.swing.JPanel();
        lblInicar = new javax.swing.JLabel();
        lblTamaño1 = new javax.swing.JLabel();
        lblTamaño2 = new javax.swing.JLabel();
        lblTamaño3 = new javax.swing.JLabel();
        lblTamaño4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(248, 242, 231));
        panelFondo.setPreferredSize(new java.awt.Dimension(416, 315));
        panelFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelFondoMousePressed(evt);
            }
        });
        panelFondo.setLayout(null);

        lblCierre.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        lblCierre.setForeground(new java.awt.Color(0, 0, 0));
        lblCierre.setText("X");
        lblCierre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCierre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCierreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCierreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCierreMouseExited(evt);
            }
        });
        panelFondo.add(lblCierre);
        lblCierre.setBounds(630, 10, 30, 32);

        lblTamaño.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTamaño.setForeground(new java.awt.Color(0, 0, 0));
        lblTamaño.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTamaño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/iconopersona.png"))); // NOI18N
        panelFondo.add(lblTamaño);
        lblTamaño.setBounds(30, 280, 40, 42);

        txtJugador2.setBackground(new java.awt.Color(210, 232, 232));
        txtJugador2.setFont(new java.awt.Font("Montserrat", 1, 28)); // NOI18N
        txtJugador2.setForeground(new java.awt.Color(0, 0, 0));
        txtJugador2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtJugador2.setBorder(null);
        txtJugador2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtJugador2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtJugador2FocusLost(evt);
            }
        });
        txtJugador2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtJugador2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtJugador2MouseExited(evt);
            }
        });
        txtJugador2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJugador2KeyTyped(evt);
            }
        });
        panelFondo.add(txtJugador2);
        txtJugador2.setBounds(80, 160, 230, 40);

        txtJugador1.setBackground(new java.awt.Color(244, 216, 204));
        txtJugador1.setFont(new java.awt.Font("Montserrat", 1, 28)); // NOI18N
        txtJugador1.setForeground(new java.awt.Color(0, 0, 0));
        txtJugador1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtJugador1.setBorder(null);
        txtJugador1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtJugador1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtJugador1FocusLost(evt);
            }
        });
        txtJugador1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtJugador1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtJugador1MouseExited(evt);
            }
        });
        txtJugador1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJugador1KeyTyped(evt);
            }
        });
        panelFondo.add(txtJugador1);
        txtJugador1.setBounds(80, 100, 230, 40);

        rbtTamañoTablero.add(rbt15x15);
        rbt15x15.setForeground(new java.awt.Color(0, 0, 0));
        rbt15x15.setText("15x15");
        panelFondo.add(rbt15x15);
        rbt15x15.setBounds(490, 230, 70, 21);

        rbtTamañoTablero.add(rbt10x10);
        rbt10x10.setForeground(new java.awt.Color(0, 0, 0));
        rbt10x10.setText("10x10");
        panelFondo.add(rbt10x10);
        rbt10x10.setBounds(490, 150, 60, 21);

        rbtTamañoTablero.add(rbt13x13);
        rbt13x13.setForeground(new java.awt.Color(0, 0, 0));
        rbt13x13.setText("13x13");
        panelFondo.add(rbt13x13);
        rbt13x13.setBounds(490, 190, 70, 21);

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Serpientes & Escaleras");
        panelFondo.add(lblTitulo);
        lblTitulo.setBounds(130, 30, 420, 42);

        txtJugador3.setBackground(new java.awt.Color(232, 229, 211));
        txtJugador3.setFont(new java.awt.Font("Montserrat", 1, 28)); // NOI18N
        txtJugador3.setForeground(new java.awt.Color(0, 0, 0));
        txtJugador3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtJugador3.setBorder(null);
        txtJugador3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtJugador3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtJugador3FocusLost(evt);
            }
        });
        txtJugador3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtJugador3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtJugador3MouseExited(evt);
            }
        });
        txtJugador3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJugador3KeyTyped(evt);
            }
        });
        panelFondo.add(txtJugador3);
        txtJugador3.setBounds(80, 220, 230, 40);

        txtJugador4.setBackground(new java.awt.Color(215, 234, 205));
        txtJugador4.setFont(new java.awt.Font("Montserrat", 1, 28)); // NOI18N
        txtJugador4.setForeground(new java.awt.Color(0, 0, 0));
        txtJugador4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtJugador4.setBorder(null);
        txtJugador4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtJugador4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtJugador4FocusLost(evt);
            }
        });
        txtJugador4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtJugador4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtJugador4MouseExited(evt);
            }
        });
        txtJugador4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJugador4KeyTyped(evt);
            }
        });
        panelFondo.add(txtJugador4);
        txtJugador4.setBounds(80, 280, 230, 40);

        panelBoton.setBackground(new java.awt.Color(90, 114, 179));

        lblInicar.setBackground(new java.awt.Color(255, 255, 255));
        lblInicar.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        lblInicar.setForeground(new java.awt.Color(0, 0, 0));
        lblInicar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInicar.setText("INICIAR");
        lblInicar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInicarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInicarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblInicarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonLayout = new javax.swing.GroupLayout(panelBoton);
        panelBoton.setLayout(panelBotonLayout);
        panelBotonLayout.setHorizontalGroup(
            panelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblInicar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBotonLayout.setVerticalGroup(
            panelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblInicar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelFondo.add(panelBoton);
        panelBoton.setBounds(440, 270, 160, 50);

        lblTamaño1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTamaño1.setForeground(new java.awt.Color(0, 0, 0));
        lblTamaño1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTamaño1.setText("Elije el tamaño del tablero:");
        panelFondo.add(lblTamaño1);
        lblTamaño1.setBounds(420, 100, 200, 42);

        lblTamaño2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTamaño2.setForeground(new java.awt.Color(0, 0, 0));
        lblTamaño2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTamaño2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/iconopersona.png"))); // NOI18N
        panelFondo.add(lblTamaño2);
        lblTamaño2.setBounds(30, 100, 40, 42);

        lblTamaño3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTamaño3.setForeground(new java.awt.Color(0, 0, 0));
        lblTamaño3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTamaño3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/iconopersona.png"))); // NOI18N
        panelFondo.add(lblTamaño3);
        lblTamaño3.setBounds(30, 160, 40, 42);

        lblTamaño4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTamaño4.setForeground(new java.awt.Color(0, 0, 0));
        lblTamaño4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTamaño4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/iconopersona.png"))); // NOI18N
        panelFondo.add(lblTamaño4);
        lblTamaño4.setBounds(30, 220, 40, 42);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ficha4.png"))); // NOI18N
        panelFondo.add(jLabel1);
        jLabel1.setBounds(330, 280, 30, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ficha1.png"))); // NOI18N
        panelFondo.add(jLabel3);
        jLabel3.setBounds(330, 100, 30, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ficha2.png"))); // NOI18N
        panelFondo.add(jLabel4);
        jLabel4.setBounds(330, 160, 30, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ficha3.png"))); // NOI18N
        panelFondo.add(jLabel5);
        jLabel5.setBounds(330, 220, 30, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFondoMousePressed
        panelFondo.requestFocus();
    }//GEN-LAST:event_panelFondoMousePressed

    private void lblInicarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicarMousePressed
        Jugador jugador1 = new Jugador();
        Jugador jugador2 = new Jugador();
        Jugador jugador3 = new Jugador();
        Jugador jugador4 = new Jugador();

        if (txtJugador1.getText().equals("")) {
            if (txtJugador1.hasFocus()) {
                txtJugador1.setText("");
            } else {
                jugador1.setNombre("");
            }
        } else {
            jugador1.setNombre(txtJugador1.getText());
        }

        if (txtJugador2.getText().equals("")) {
            if (txtJugador2.hasFocus()) {
                txtJugador2.setText("");
            } else {
                jugador2.setNombre("");
            }
        } else {
            jugador2.setNombre(txtJugador2.getText());
        }

        if (txtJugador3.getText().equals("")) {
            jugador3.setNombre("");
        } else {
            jugador3.setNombre(txtJugador3.getText());
        }

        if (txtJugador4.getText().equals("")) {
            jugador4.setNombre("");
        } else {
            jugador4.setNombre(txtJugador4.getText());
        }

        int tamañoTablero = 0;

        if (rbt10x10.isSelected()) {
            tamañoTablero = 10;
        } else if (rbt13x13.isSelected()) {
            tamañoTablero = 13;
        } else if (rbt15x15.isSelected()) {
            tamañoTablero = 15;
        }

        if (!txtJugador1.getText().isEmpty() && !txtJugador2.getText().isEmpty() && tamañoTablero != 0) {
            List<Jugador> jugadores = new ArrayList<>();
            jugadores.add(jugador1);
            jugadores.add(jugador2);

            if (!txtJugador3.getText().isEmpty()) {
                jugadores.add(jugador3);
            }

            if (!txtJugador4.getText().isEmpty()) {
                jugadores.add(jugador4);
            }

            PanelTablero_SerpientesyEscaleras panelTablero = new PanelTablero_SerpientesyEscaleras(jugadores, tamañoTablero);
            panelTablero.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Faltan campos por llenar.", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblInicarMousePressed

    private void lblInicarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicarMouseExited
        panelBoton.setBackground(new Color(90, 114, 179));
    }//GEN-LAST:event_lblInicarMouseExited

    private void lblInicarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicarMouseEntered
        panelBoton.setBackground(new Color(120, 142, 205));
    }//GEN-LAST:event_lblInicarMouseEntered

    private void txtJugador1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJugador1KeyTyped
        char caracter = Character.toLowerCase(evt.getKeyChar());
        evt.setKeyChar(caracter);
        if (txtJugador1.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtJugador1KeyTyped

    private void txtJugador1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJugador1MouseExited
        txtJugador1.setBorder(null);
    }//GEN-LAST:event_txtJugador1MouseExited

    private void txtJugador1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJugador1MouseEntered
        Border borde = BorderFactory.createLineBorder(new Color(230, 167, 136), 2);
        txtJugador1.setBorder(borde);
    }//GEN-LAST:event_txtJugador1MouseEntered

    private void txtJugador1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJugador1FocusLost
        if (txtJugador1.getText().trim().equals("")) {
            txtJugador1.setText("");
        }
    }//GEN-LAST:event_txtJugador1FocusLost

    private void txtJugador1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJugador1FocusGained
        if (txtJugador1.getText().equals("Jugador 1")) {
            txtJugador1.setText("");
        }
    }//GEN-LAST:event_txtJugador1FocusGained

    private void txtJugador2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJugador2KeyTyped
        char caracter = Character.toLowerCase(evt.getKeyChar());
        evt.setKeyChar(caracter);
        if (txtJugador2.getText().length() >= 10)
            evt.consume();
    }//GEN-LAST:event_txtJugador2KeyTyped

    private void txtJugador2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJugador2MouseExited
        txtJugador2.setBorder(null);
    }//GEN-LAST:event_txtJugador2MouseExited

    private void txtJugador2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJugador2MouseEntered
        Border borde = BorderFactory.createLineBorder(new Color(137, 169, 192), 2);
        txtJugador2.setBorder(borde);
    }//GEN-LAST:event_txtJugador2MouseEntered

    private void txtJugador2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJugador2FocusLost
        if (txtJugador2.getText().trim().equals("")) {
            txtJugador2.setText("");
        }
    }//GEN-LAST:event_txtJugador2FocusLost

    private void txtJugador2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJugador2FocusGained
        if (txtJugador2.getText().equals("Jugador 2")) {
            txtJugador2.setText("");
        }
    }//GEN-LAST:event_txtJugador2FocusGained

    private void lblCierreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCierreMouseExited
        lblCierre.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_lblCierreMouseExited

    private void lblCierreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCierreMouseEntered
        lblCierre.setForeground(Color.RED);
    }//GEN-LAST:event_lblCierreMouseEntered

    private void lblCierreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCierreMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCierreMouseClicked

    private void txtJugador3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJugador3FocusLost
        if (txtJugador3.getText().trim().equals("")) {
            txtJugador3.setText("");
        }
    }//GEN-LAST:event_txtJugador3FocusLost

    private void txtJugador3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJugador3MouseEntered
        Border borde = BorderFactory.createLineBorder(new Color(208, 218, 235), 2);
        txtJugador3.setBorder(borde);
    }//GEN-LAST:event_txtJugador3MouseEntered

    private void txtJugador3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJugador3MouseExited
        txtJugador3.setBorder(null);
    }//GEN-LAST:event_txtJugador3MouseExited

    private void txtJugador3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJugador3KeyTyped
        char caracter = Character.toLowerCase(evt.getKeyChar());
        evt.setKeyChar(caracter);
        if (txtJugador3.getText().length() >= 10)
            evt.consume();
    }//GEN-LAST:event_txtJugador3KeyTyped

    private void txtJugador4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJugador4FocusGained
        if (txtJugador4.getText().equals("Jugador 4")) {
            txtJugador4.setText("");
        }
    }//GEN-LAST:event_txtJugador4FocusGained

    private void txtJugador4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJugador4FocusLost
        if (txtJugador4.getText().trim().equals("")) {
            txtJugador4.setText("");
        }
    }//GEN-LAST:event_txtJugador4FocusLost

    private void txtJugador4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJugador4MouseEntered
        Border borde = BorderFactory.createLineBorder(new Color(135, 183, 159), 2);
        txtJugador4.setBorder(borde);
    }//GEN-LAST:event_txtJugador4MouseEntered

    private void txtJugador4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJugador4MouseExited
        txtJugador4.setBorder(null);
    }//GEN-LAST:event_txtJugador4MouseExited

    private void txtJugador4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJugador4KeyTyped
        char caracter = Character.toLowerCase(evt.getKeyChar());
        evt.setKeyChar(caracter);
        if (txtJugador4.getText().length() >= 10)
            evt.consume();
    }//GEN-LAST:event_txtJugador4KeyTyped

    private void txtJugador3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJugador3FocusGained
        if (txtJugador3.getText().equals("Jugador 3")) {
            txtJugador3.setText("");
        }
    }//GEN-LAST:event_txtJugador3FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelMain_SerpientesyEscaleras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelMain_SerpientesyEscaleras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelMain_SerpientesyEscaleras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelMain_SerpientesyEscaleras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelMain_SerpientesyEscaleras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCierre;
    private javax.swing.JLabel lblInicar;
    private javax.swing.JLabel lblTamaño;
    private javax.swing.JLabel lblTamaño1;
    private javax.swing.JLabel lblTamaño2;
    private javax.swing.JLabel lblTamaño3;
    private javax.swing.JLabel lblTamaño4;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelBoton;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JRadioButton rbt10x10;
    private javax.swing.JRadioButton rbt13x13;
    private javax.swing.JRadioButton rbt15x15;
    private javax.swing.ButtonGroup rbtJugadores;
    private javax.swing.ButtonGroup rbtTamañoTablero;
    private javax.swing.JTextField txtJugador1;
    private javax.swing.JTextField txtJugador2;
    private javax.swing.JTextField txtJugador3;
    private javax.swing.JTextField txtJugador4;
    // End of variables declaration//GEN-END:variables

}
